### ISSUE TITLE
sporadic helgrind, drd test failures

### ISSUE THREAD

**Issue by GBuella** [marcinslusarz/pmemfile#5]
The test mt_drd and mt_helgrind fail sometimes.
The attached logs were created while using NVML built from pmemfile.v12 branch, 577f55c6f42b1b27227f4654c44a60492f4e9e36

and pmemfile f3aca45b1505490b07b2694af00a662abf68e9e9

[mt_drd_fail.txt](https://github.com/marcinslusarz/pmemfile/files/806915/mt_drd_fail.txt)
[mt_helgrind_fail.txt](https://github.com/marcinslusarz/pmemfile/files/806916/mt_helgrind_fail.txt)

**Comment by GBuella** [comment]
Well, I tried with NVML master at f3aca45b1505490b07b2694af00a662abf68e9e9
and the failures seem to have disappeared.

**Comment by marcinslusarz** [comment]
It's probably because of @pbalcer Valgrind-related changes, which were merged recently.
